export const refs={
    header: document.querySelector('header'),
    deliveryWrapper: document.querySelector('.header-delivery-wrapper'),
    headerInput: document.querySelector('.input-mobile'),
    togglerButtons: Array.from(document.querySelectorAll('.header-toggler-button')),
    iconList: document.querySelector('.header-icon-list'),
    cart: document.querySelector('.registr-cart'),
    cartMobile: document.querySelector('.mobile-cart'),
    container: document.querySelector('.container'),
    registrBtnBlock: document.querySelector('.registr-wrapper'),
    heroSection: document.querySelector('.section-hero'),
    cartButtons: document.querySelector('.registr-cart-buttons'),
    menuWrapper:document.querySelector('.menu-wrapper'),
    backdrop:document.querySelector('.backdrop'),
    navList:document.querySelector('.navigation-list'),
    navListItem: Array.from(document.querySelectorAll('.navigation-list-item')),
    categoryBlock: document.querySelector('.category-block'),
    iconGoBack:document.querySelector('.icon-back'),
    mobileDelivery: document.querySelector('.delivery-wrapper'),
    deliverySlogan:document.querySelector('.delivery-slogan'),
}